# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sensor_stream.proto\x12\rsensor_stream\"m\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02qw\x18\x04 \x01(\x01\x12\n\n\x02qx\x18\x05 \x01(\x01\x12\n\n\x02qy\x18\x06 \x01(\x01\x12\n\n\x02qz\x18\x07 \x01(\x01\x12\x14\n\x0ctimestamp_us\x18\x08 \x01(\x04\"a\n\nImageFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\"v\n\nDepthFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65pth_scale\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_us\x18\x06 \x01(\x04\"\xa1\x01\n\nSensorData\x12!\n\x04pose\x18\x01 \x01(\x0b\x32\x13.sensor_stream.Pose\x12.\n\x0b\x63olor_image\x18\x02 \x01(\x0b\x32\x19.sensor_stream.ImageFrame\x12.\n\x0b\x64\x65pth_image\x18\x03 \x01(\x0b\x32\x19.sensor_stream.DepthFrame\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\x04\"K\n\x0eStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x66rames_received\x18\x03 \x01(\x04\x32\xae\x01\n\x13SensorStreamService\x12P\n\x10StreamSensorData\x12\x19.sensor_stream.SensorData\x1a\x1d.sensor_stream.StreamResponse(\x01\x30\x01\x12\x45\n\tSendFrame\x12\x19.sensor_stream.SensorData\x1a\x1d.sensor_stream.StreamResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=38
  _globals['_POSE']._serialized_end=147
  _globals['_IMAGEFRAME']._serialized_start=149
  _globals['_IMAGEFRAME']._serialized_end=246
  _globals['_DEPTHFRAME']._serialized_start=248
  _globals['_DEPTHFRAME']._serialized_end=366
  _globals['_SENSORDATA']._serialized_start=369
  _globals['_SENSORDATA']._serialized_end=530
  _globals['_STREAMRESPONSE']._serialized_start=532
  _globals['_STREAMRESPONSE']._serialized_end=607
  _globals['_SENSORSTREAMSERVICE']._serialized_start=610
  _globals['_SENSORSTREAMSERVICE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
